site_name: Pastafari documentation
pages:
- Home: index.md
- Installation: install.md
- User Guide: userguide.md
- Task development: taskdevelopment.md
- Deploying: deploying.md
- About: about.md
theme: readthedocs
